version: "3"
services:

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"


  service-um:
    build: './service-um'
    container_name: service-um
    depends_on:
    - mongo
    environment:
    - MONGODB_URI= mongodb://mongo:27017/orders-db
    ports:
      - "8083:8083"

